# Generated by Django 5.2.8 on 2026-05-02 12:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FensterTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('u_w', models.FloatField(help_text='Uw-Wert W/m²K', validators=[django.core.validators.MinValueValidator(0)])),
                ('g_value', models.FloatField(help_text='g-Wert (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)])),
                ('psi_edge', models.FloatField(default=0.06, help_text='Ψ_Randverbund W/mK')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Gebäude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('standort', models.CharField(blank=True, max_length=200)),
                ('bgf', models.FloatField(help_text='Brutto-Grundfläche m²', validators=[django.core.validators.MinValueValidator(0)])),
                ('gradstunden', models.FloatField(default=78000, help_text='Gradstunden/Jahr Kh/a')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Konstruktion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('typ', models.CharField(choices=[('aussen_wand', 'Außenwand'), ('dach', 'Dach'), ('bodenplatte', 'Bodenplatte'), ('decke', 'Decke/Zwischendecke'), ('keller_wand', 'Kellerwand')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('r_si', models.FloatField(default=0.13, help_text='R_si Wärmewiderstand innen (m²K/W)')),
                ('r_se', models.FloatField(default=0.04, help_text='R_se Wärmewiderstand außen (m²K/W)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['typ', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rohdichte', models.FloatField(help_text='kg/m³', validators=[django.core.validators.MinValueValidator(0)])),
                ('lambda_value', models.FloatField(help_text='W/mK', validators=[django.core.validators.MinValueValidator(0)])),
                ('c_specific', models.FloatField(default=1.0, help_text='kJ/kgK', validators=[django.core.validators.MinValueValidator(0)])),
                ('mu_value', models.FloatField(default=1.0, help_text='Wasserdampf-Diffusionswiderstand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SonnenschutzTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('position', models.CharField(choices=[('innen', 'Innen'), ('außen', 'Außen')], max_length=10)),
                ('typ', models.CharField(choices=[('fest', 'Fest'), ('variabel', 'Variabel')], max_length=10)),
                ('reduktionsfaktor', models.FloatField(help_text='Reduktionsfaktor (0-1)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TürTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('u_value', models.FloatField(help_text='U-Wert W/m²K', validators=[django.core.validators.MinValueValidator(0)])),
                ('luftdichtheit', models.FloatField(default=1.0, help_text='Luftdichtheitsklasse (m³/h·m²)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaterialSchicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness_mm', models.FloatField(help_text='Schichtdicke mm', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.material')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='KonstruktionSchicht',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('konstruktion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.konstruktion')),
                ('schicht', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.materialschicht')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('konstruktion', 'schicht', 'order')},
            },
        ),
        migrations.AddField(
            model_name='konstruktion',
            name='schichten',
            field=models.ManyToManyField(through='dashboard.KonstruktionSchicht', to='dashboard.materialschicht'),
        ),
        migrations.CreateModel(
            name='Bauteil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('orientierung', models.CharField(choices=[('nord', 'Nord'), ('süd', 'Süd'), ('ost', 'Ost'), ('west', 'West'), ('horizontal', 'Horizontal (Dach/Boden)')], max_length=15)),
                ('fläche', models.FloatField(help_text='m²', validators=[django.core.validators.MinValueValidator(0)])),
                ('fenster_fläche', models.FloatField(default=0, help_text='Fensterfläche m²', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fenster_typ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fenstertyp')),
                ('gebäude', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bauteile', to='dashboard.gebäude')),
                ('konstruktion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.konstruktion')),
                ('sonnenschutz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.sonnenschutztyp')),
            ],
            options={
                'ordering': ['orientierung', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='konstruktion',
            unique_together={('name', 'typ')},
        ),
    ]
